name: Generate Release PDF
on: 
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '**.md'
env:
  TYPST_FILE_NAME: Riemann_surfaces
jobs:
  build_typst:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Download Computer Modern Sans Serif Fonts
        run: |
          echo "Github: Downloading Computer Modern Sans Serif font family..."
          run: |
          sudo mkdir -p /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans08-Book.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans08-BookOblique.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans08-Oblique.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans08-Regular.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans10-Bold.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans10-BoldOblique.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans10-Book.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans10-BookOblique.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans10-Oblique.otf -P /usr/share/fonts/opentype/newcomputermodern
          sudo wget https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf/NewCMSans10-Regular.otf -P /usr/share/fonts/opentype/newcomputermodern
          echo "Github: Rebuild font cache"
          sudo fc-cache -f -v
          echo "Github: Download complete."
      - name: List Installed Fonts
        run: |
          echo "Github: Listing all installed fonts..."
          fc-list
          typst fonts
      - name: Compile Typst document
        uses: lvignoli/typst-action@main
        with:
          source_file: ${{ env.TYPST_FILE_NAME }}.typ
      - name: Delete old Release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            try {
              const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo })
              await github.rest.repos.deleteRelease({ owner, repo, release_id: id })
            } catch {}
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::latest_$(date +"%Y-%m-%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest version
          body: Latest version of `${{ env.TYPST_FILE_NAME }}.pdf`
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ${{ env.TYPST_FILE_NAME }}.pdf
