name: Generate Release PDF
on: 
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '**.md'
env:
  TYPST_FILE_NAME: Riemann_surfaces
jobs:
  build_typst:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install Computer Modern Fonts
        run: |
          wget -O computer-modern.zip https://www.fontsquirrel.com/fonts/download/computer-modern
          unzip -d computer-modern/ computer-modern.zip
          mv computer-modern /usr/share/fonts/
          fc-cache -fv
          fc-list
      - name: Compile Typst document
        uses: lvignoli/typst-action@main
        with:
          source_file: ${{ env.TYPST_FILE_NAME }}.typ
      - name: Delete old Release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            try {
              const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo })
              await github.rest.repos.deleteRelease({ owner, repo, release_id: id })
            } catch {}
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::latest_$(date +"%Y-%m-%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest version
          body: Latest version of `${{ env.TYPST_FILE_NAME }}.pdf`
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ${{ env.TYPST_FILE_NAME }}.pdf
