name: Generate Release PDF
on: 
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '**.md'
env:
  TYPST_FILE_NAME: Riemann_surfaces
jobs:
  build_typst:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Download Computer Modern Sans Serif Fonts
        run: |
          echo "Downloading Computer Modern Sans Serif font family..."
          wget -O cm_sans.zip https://www.ctan.org/tex-archive/fonts/newcomputermodern/otf
          echo "Download complete."

      - name: Unzip and Install Fonts
        run: |
          echo "Unzipping the font package..."
          unzip -d cm_sans/ cm_sans.zip
          echo "Moving fonts to the system fonts directory..."
          sudo mv cm_sans /usr/share/fonts/
          echo "Fonts moved successfully."
          echo "Refreshing the font cache..."
          sudo fc-cache -fv
          echo "Font cache refreshed."
      - name: List Installed Fonts
        run: |
          echo "Listing all installed fonts..."
          fc-list
          typst fonts
      - name: Compile Typst document
        uses: lvignoli/typst-action@main
        with:
          source_file: ${{ env.TYPST_FILE_NAME }}.typ
      - name: Delete old Release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            try {
              const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo })
              await github.rest.repos.deleteRelease({ owner, repo, release_id: id })
            } catch {}
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::latest_$(date +"%Y-%m-%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest version
          body: Latest version of `${{ env.TYPST_FILE_NAME }}.pdf`
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ${{ env.TYPST_FILE_NAME }}.pdf
